name: Build and Attach EXE to Release

permissions:
  contents: write

on:
  release:
    types: [published]

jobs:
  build-and-upload:
    runs-on: windows-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v3

      - name: Make dist folder
        run: mkdir dist

      - name: Compile ER Death Counter.exe
        shell: cmd
        run: |
          compiler\Ahk2Exe.exe ^
            /in deathcounter.ahk ^
            /out "dist\ER-Death-Counter.exe" ^
            /base compiler\AutoHotkey64.exe ^
            /icon assets\gold_circle.ico

      - name: Upload EXE to this Release
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ github.event.release.upload_url }}
          asset_path: "dist/ER-Death-Counter.exe"
          asset_name: ER-Death-Counter.exe
          asset_content_type: application/octet-stream
